/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Utils.Analizador;
import Utils.Files;

import java.awt.Cursor;
import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileFilter;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Luisa María Ortiz
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Files fs;
    Analizador analizador;
    public Principal() {
        initComponents();
        fs = new Files();
        analizador = new Analizador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_code = new javax.swing.JTextPane();
        jLabel_errors = new javax.swing.JLabel();
        jLabel_errorsName = new javax.swing.JLabel();
        jButton_clean = new javax.swing.JButton();
        jButton_run = new javax.swing.JButton();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_openFile = new javax.swing.JMenuItem();
        jMenuItem_saveAs = new javax.swing.JMenuItem();
        jMenu_Report = new javax.swing.JMenu();
        jMenuItem_flowChart = new javax.swing.JMenuItem();
        jMenuItem_errors = new javax.swing.JMenuItem();
        jMenuItem_ast = new javax.swing.JMenuItem();
        jMenu_View = new javax.swing.JMenu();
        jMenuItem_userManual = new javax.swing.JMenuItem();
        jMenuItem_technicalManual = new javax.swing.JMenuItem();
        jMenuItem_gramar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project 1 OLC1 ");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("OLC1_2S_2022 <202003381>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, -1, -1));

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        jTextPane_code.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane_code.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jTextPane_code.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jTextPane_code);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1300, 430));

        jLabel_errors.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel_errors.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_errors.setText("0");
        jPanel1.add(jLabel_errors, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 180, -1));

        jLabel_errorsName.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_errorsName.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel_errorsName.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_errorsName.setText("Errors:");
        jPanel1.add(jLabel_errorsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));

        jButton_clean.setBackground(new java.awt.Color(0, 153, 153));
        jButton_clean.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton_clean.setForeground(new java.awt.Color(255, 255, 255));
        jButton_clean.setText("Clean");
        jButton_clean.setToolTipText("Clean the text area.");
        jButton_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cleanActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 90, 90, 40));

        jButton_run.setBackground(new java.awt.Color(51, 153, 0));
        jButton_run.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton_run.setForeground(new java.awt.Color(255, 255, 255));
        jButton_run.setText("Run");
        jButton_run.setToolTipText("Translate the pseudocode.");
        jButton_run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_runActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_run, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 90, 90, 40));

        jComboBox.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jComboBox.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Golang", "Python" }));
        jPanel1.add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1205, 590, 110, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Language:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 590, -1, 30));

        jMenu_File.setText("File");
        jMenu_File.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N

        jMenuItem_openFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_openFile.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jMenuItem_openFile.setText("Open File");
        jMenuItem_openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_openFileActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_openFile);

        jMenuItem_saveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_saveAs.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jMenuItem_saveAs.setText("Save As...");
        jMenuItem_saveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_saveAsActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_saveAs);

        jMenuBar.add(jMenu_File);

        jMenu_Report.setText("Report");
        jMenu_Report.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N

        jMenuItem_flowChart.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jMenuItem_flowChart.setText("FlowChart");
        jMenuItem_flowChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_flowChartActionPerformed(evt);
            }
        });
        jMenu_Report.add(jMenuItem_flowChart);

        jMenuItem_errors.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jMenuItem_errors.setText("Errors");
        jMenuItem_errors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_errorsActionPerformed(evt);
            }
        });
        jMenu_Report.add(jMenuItem_errors);

        jMenuItem_ast.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jMenuItem_ast.setText("AST");
        jMenuItem_ast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_astActionPerformed(evt);
            }
        });
        jMenu_Report.add(jMenuItem_ast);

        jMenuBar.add(jMenu_Report);

        jMenu_View.setText("View");
        jMenu_View.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N

        jMenuItem_userManual.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jMenuItem_userManual.setText("User manual");
        jMenuItem_userManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_userManualActionPerformed(evt);
            }
        });
        jMenu_View.add(jMenuItem_userManual);

        jMenuItem_technicalManual.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jMenuItem_technicalManual.setText("Technical manual");
        jMenuItem_technicalManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_technicalManualActionPerformed(evt);
            }
        });
        jMenu_View.add(jMenuItem_technicalManual);

        jMenuItem_gramar.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jMenuItem_gramar.setText("Grammar");
        jMenuItem_gramar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gramarActionPerformed(evt);
            }
        });
        jMenu_View.add(jMenuItem_gramar);

        jMenuBar.add(jMenu_View);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1338, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_openFileActionPerformed
        JFileChooser selectArchivo = new JFileChooser();
        selectArchivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("OLC FILES","olc");
        selectArchivo.setFileFilter(filter);
        int result = selectArchivo.showOpenDialog(this);
        File archivo = selectArchivo.getSelectedFile();
        
        if(archivo==null || archivo.getName().equals("")){
            JOptionPane.showMessageDialog(this, "Archivo invalido","Archivo invalido",JOptionPane.ERROR_MESSAGE);
        }
        else{
            jTextPane_code.setText(fs.readFile(archivo));
        }
        
    }//GEN-LAST:event_jMenuItem_openFileActionPerformed

    private void jButton_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cleanActionPerformed
        this.jTextPane_code.setText("");
    }//GEN-LAST:event_jButton_cleanActionPerformed

    private void jButton_runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_runActionPerformed
        // TODO add your handling code here:
        
        
       // System.out.println( analizador.interpretar(jTextPane_code.getText()));
    	
       String trad = analizador.interpretar(jTextPane_code.getText(),(int)jComboBox.getSelectedIndex());
       this.jLabel_errors.setText(String.valueOf(analizador.noErrores));
       Traduccion traduccion = new Traduccion ((int)jComboBox.getSelectedIndex(),trad);
       traduccion.setVisible(true);
    }//GEN-LAST:event_jButton_runActionPerformed

    private void jMenuItem_saveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_saveAsActionPerformed
        
    	try { 

        	JFileChooser selectArchivo = new JFileChooser();
          //  selectArchivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        	FileNameExtensionFilter filter;
        	String extension=".olc";
        
                filter = new FileNameExtensionFilter("OLC FILE","olc");
                
            selectArchivo.setFileFilter(filter);
            int result = selectArchivo.showOpenDialog(this);
            File file = selectArchivo.getSelectedFile();
            
            
            if(file==null || file.getName().equals("")){
                JOptionPane.showMessageDialog(this, "Ruta no valida","Ruta no valida",JOptionPane.ERROR_MESSAGE);
            }
            
                
            File fin = new File(file.getAbsoluteFile()+extension);
          
             // Si el archivo no existe es creado
             if (!fin.exists()) {
                 fin.createNewFile();
             }
             FileWriter fw = new FileWriter(fin);
             BufferedWriter bw = new BufferedWriter(fw);
             
             
    			bw.write(this.jTextPane_code.getText());
    			bw.close();
    			 JOptionPane.showMessageDialog(this, "Archivo guardado","Archivo guardado",JOptionPane.INFORMATION_MESSAGE);
    		} catch (IOException e) {
    			 JOptionPane.showMessageDialog(this, "Error al guardar archivo","Error al guardar archivo",JOptionPane.ERROR_MESSAGE);
    			
    			e.printStackTrace();
    		}
    }//GEN-LAST:event_jMenuItem_saveAsActionPerformed

    private void jMenuItem_flowChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_flowChartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_flowChartActionPerformed

    private void jMenuItem_errorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_errorsActionPerformed
      try {
		Desktop.getDesktop().open(new File("reportes/errores.html"));
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
    }//GEN-LAST:event_jMenuItem_errorsActionPerformed

    private void jMenuItem_astActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_astActionPerformed
       if( analizador.generarArbol(this.jTextPane_code.getText())) {
    	   try {
    		this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
			Thread.sleep(3000);
			this.setCursor(Cursor.DEFAULT_CURSOR);
			Desktop.getDesktop().open(new File("reportes/ast.png"));
		} catch (InterruptedException | IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
       }
        
        
        //TODO: Si es true, que lo muestre
    }//GEN-LAST:event_jMenuItem_astActionPerformed

    private void jMenuItem_userManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_userManualActionPerformed
        try {
    		Desktop.getDesktop().open(new File("Manuales/Manual de usuario.pdf"));
    	} catch (IOException e) {
    		
    		e.printStackTrace();
    	}
    }//GEN-LAST:event_jMenuItem_userManualActionPerformed

    private void jMenuItem_technicalManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_technicalManualActionPerformed
    	try {
    		Desktop.getDesktop().open(new File("Manuales/Manual tecnico.pdf"));
    	} catch (IOException e) {
    	
    		e.printStackTrace();
    	}
    }//GEN-LAST:event_jMenuItem_technicalManualActionPerformed

    private void jMenuItem_gramarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gramarActionPerformed
    	try {
    		Desktop.getDesktop().open(new File("Manuales/Gramatica.pdf"));
    	} catch (IOException e) {
    		
    		e.printStackTrace();
    	}
    }//GEN-LAST:event_jMenuItem_gramarActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_clean;
    private javax.swing.JButton jButton_run;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_errors;
    private javax.swing.JLabel jLabel_errorsName;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem_ast;
    private javax.swing.JMenuItem jMenuItem_errors;
    private javax.swing.JMenuItem jMenuItem_flowChart;
    private javax.swing.JMenuItem jMenuItem_gramar;
    private javax.swing.JMenuItem jMenuItem_openFile;
    private javax.swing.JMenuItem jMenuItem_saveAs;
    private javax.swing.JMenuItem jMenuItem_technicalManual;
    private javax.swing.JMenuItem jMenuItem_userManual;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JMenu jMenu_Report;
    private javax.swing.JMenu jMenu_View;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane_code;
    // End of variables declaration//GEN-END:variables
}
