/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.FocusListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Luisa María Ortiz
 */
public class Traduccion extends javax.swing.JFrame {

    /**
     * Creates new form Traduccion
     */
    public int lenguaje; //0-> Go, 1->Python
    public Traduccion(int lenguaje, String traduccion) {
        this.lenguaje=lenguaje;
     
        initComponents();
        
        if(lenguaje==0) {
        	this.jLabel_lenguaje.setText("Golang");
        	this.jButton_guardar.setText("Guardar .go");
        }
        else {
        	this.jLabel_lenguaje.setText("Python");
        	this.jButton_guardar.setText("Guardar .py");
        }
        
        this.jTextArea_traduccion.setText(traduccion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_lenguaje = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_traduccion = new javax.swing.JTextArea();
        jButton_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Traduccion");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Traducción: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel_lenguaje.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel_lenguaje.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_lenguaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel1.add(jLabel_lenguaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 80, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(102, 102, 102));

        jTextArea_traduccion.setEditable(false);
        jTextArea_traduccion.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_traduccion.setColumns(20);
        jTextArea_traduccion.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextArea_traduccion.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea_traduccion.setRows(5);
        jScrollPane1.setViewportView(jTextArea_traduccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 880, 410));

        jButton_guardar.setBackground(new java.awt.Color(0, 102, 102));
        jButton_guardar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed

    	try { 

    	JFileChooser selectArchivo = new JFileChooser();
      //  selectArchivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    	FileNameExtensionFilter filter;
    	String extension="";
    	if(this.lenguaje==0) {
            filter = new FileNameExtensionFilter("GOLANG FILE","go");
            extension=".go";
            }
            else {
            	 filter = new FileNameExtensionFilter("PYTHON FILE","py");
            	 extension=".py";
            }
            selectArchivo.setFileFilter(filter);
        int result = selectArchivo.showOpenDialog(this);
        File file = selectArchivo.getSelectedFile();
        
        
        if(file==null || file.getName().equals("")){
            JOptionPane.showMessageDialog(this, "Ruta no valida","Ruta no valida",JOptionPane.ERROR_MESSAGE);
        }
        
            
        File fin = new File(file.getAbsoluteFile()+extension);
      
         // Si el archivo no existe es creado
         if (!fin.exists()) {
             fin.createNewFile();
         }
         FileWriter fw = new FileWriter(fin);
         BufferedWriter bw = new BufferedWriter(fw);
         
         
			bw.write(this.jTextArea_traduccion.getText());
			bw.close();
			 JOptionPane.showMessageDialog(this, "Archivo guardado","Archivo guardado",JOptionPane.INFORMATION_MESSAGE);
		} catch (IOException e) {
			 JOptionPane.showMessageDialog(this, "Error al guardar archivo","Error al guardar archivo",JOptionPane.ERROR_MESSAGE);
			
			e.printStackTrace();
		}
         
    
    }//GEN-LAST:event_jButton_guardarActionPerformed

   
	

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_lenguaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_traduccion;
    // End of variables declaration//GEN-END:variables
}
