
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int comentarioSimple = 27;
  public static final int como = 30;
  public static final int finMientras = 51;
  public static final int finFuncion = 59;
  public static final int imprimir = 61;
  public static final int mod = 13;
  public static final int flecha = 35;
  public static final int conValor = 31;
  public static final int hasta = 46;
  public static final int comentarioMultiple = 28;
  public static final int parentesisCierra = 15;
  public static final int hastaQue = 53;
  public static final int coma = 33;
  public static final int finSi = 38;
  public static final int inicio = 25;
  public static final int t_cadena = 3;
  public static final int caracter = 67;
  public static final int repetir = 52;
  public static final int menorIgual = 19;
  public static final int entonses = 37;
  public static final int dividido = 9;
  public static final int si = 36;
  public static final int corcheteAbre = 11;
  public static final int mientras = 50;
  public static final int puntoycoma = 32;
  public static final int parentesisAbre = 14;
  public static final int menos = 7;
  public static final int menor = 17;
  public static final int finSegun = 44;
  public static final int corcheteCierra = 12;
  public static final int EOF = 0;
  public static final int mas = 6;
  public static final int para = 45;
  public static final int mayorIgual = 18;
  public static final int error = 1;
  public static final int mayor = 16;
  public static final int entero = 63;
  public static final int metodo = 55;
  public static final int esIgual = 20;
  public static final int or = 22;
  public static final int incremental = 48;
  public static final int por = 8;
  public static final int esDifetente = 21;
  public static final int funcion = 58;
  public static final int potencia = 10;
  public static final int finPara = 49;
  public static final int segun = 41;
  public static final int hacer = 47;
  public static final int t_numero = 2;
  public static final int variable = 34;
  public static final int ingresar = 29;
  public static final int fin = 26;
  public static final int deLoContraro = 39;
  public static final int and = 23;
  public static final int not = 24;
  public static final int booleano = 66;
  public static final int t_boolean = 4;
  public static final int retornar = 54;
  public static final int interrogacionAbre = 42;
  public static final int t_caracter = 5;
  public static final int interrogacionCierra = 43;
  public static final int conParametros = 57;
  public static final int ejecutar = 60;
  public static final int oSi = 40;
  public static final int decimal = 64;
  public static final int imprimirNl = 62;
  public static final int cadena = 65;
  public static final int finMetodo = 56;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "t_numero",
  "t_cadena",
  "t_boolean",
  "t_caracter",
  "mas",
  "menos",
  "por",
  "dividido",
  "potencia",
  "corcheteAbre",
  "corcheteCierra",
  "mod",
  "parentesisAbre",
  "parentesisCierra",
  "mayor",
  "menor",
  "mayorIgual",
  "menorIgual",
  "esIgual",
  "esDifetente",
  "or",
  "and",
  "not",
  "inicio",
  "fin",
  "comentarioSimple",
  "comentarioMultiple",
  "ingresar",
  "como",
  "conValor",
  "puntoycoma",
  "coma",
  "variable",
  "flecha",
  "si",
  "entonses",
  "finSi",
  "deLoContraro",
  "oSi",
  "segun",
  "interrogacionAbre",
  "interrogacionCierra",
  "finSegun",
  "para",
  "hasta",
  "hacer",
  "incremental",
  "finPara",
  "mientras",
  "finMientras",
  "repetir",
  "hastaQue",
  "retornar",
  "metodo",
  "finMetodo",
  "conParametros",
  "funcion",
  "finFuncion",
  "ejecutar",
  "imprimir",
  "imprimirNl",
  "entero",
  "decimal",
  "cadena",
  "booleano",
  "caracter"
  };
}

